### ISSUE TITLE
常见的面试题

### ISSUE THREAD

**Issue by LiuL0703** [LiuL0703/blog#24]
#### 左边固定，右边自适应
```html
<div class="box">
<div class="left"></div>
<div class="right"></div>
</div>
```
1. position + margin-left
```css
.box{ display: relative }
.left{ position: absolute; width:100px }
.right{ margin-left:100px }
```
2. flex
```css
.box{display:flex;}
.left{width:100px; }
.right { flex:1;}
```
